<?php
/*
 * WebhooksRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WebhooksRESTAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CreateANewWebHookRequest implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $url public property
     */
    public $url;

    /**
     * @todo Write general description for this property
     * @required
     * @var array $eventTypes public property
     */
    public $eventTypes;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $status public property
     */
    public $status;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $url        Initialization value for $this->url
     * @param array  $eventTypes Initialization value for $this->eventTypes
     * @param string $status     Initialization value for $this->status
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->url        = func_get_arg(0);
            $this->eventTypes = func_get_arg(1);
            $this->status     = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['url']        = $this->url;
        $json['eventTypes'] = $this->eventTypes;
        $json['status']     = $this->status;

        return $json;
    }
}
