<?php
/*
 * WebhooksRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace WebhooksRESTAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://example.com';

    /**
     * The username to use with basic authentication
     * @var string
     */
    /**
     * @todo Replace the $basicAuthUserName with an appropriate value
     */
    public static $basicAuthUserName = 'TODO: Replace';

    /**
     * The password to use with basic authentication
     * @var string
     */
    /**
     * @todo Replace the $basicAuthPassword with an appropriate value
     */
    public static $basicAuthPassword = 'TODO: Replace';
}
